# Generated by Django 5.0.3 on 2024-03-25 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='division_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.division'),
        ),
    ]
