# Generated by Django 5.0.3 on 2024-03-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_division_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_community_enrolled',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_university_enrolled',
            field=models.IntegerField(null=True),
        ),
    ]
