# Generated by Django 5.0.3 on 2024-03-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_major_alter_user_year_community_enrolled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permission_id',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='division_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='division_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role_description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_name',
        ),
        migrations.AddField(
            model_name='division',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='created_by',
            field=models.CharField(default='system', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='updated_by',
            field=models.CharField(default='system', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.CharField(default='system', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.CharField(default='system', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_uri',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='08', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_uri',
            field=models.ImageField(default='test', upload_to='uploads/user/profile/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_community_enrolled',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_university_enrolled',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
