# Generated by Django 5.0.3 on 2024-05-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
