# Generated by Django 5.0.3 on 2024-05-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_logo_division_logo_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
