# Generated by Django 5.0.3 on 2024-05-08 21:47

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='logo_uri',
            field=models.ImageField(null=True, upload_to='uploads/divisions/logo/', validators=[common.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_uri',
            field=models.ImageField(upload_to='uploads/user/profile/', validators=[common.validators.validate_image_size]),
        ),
    ]
