# Generated by Django 5.0.3 on 2024-08-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_division_logo_uri_alter_user_profile_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='year_community_enrolled',
        ),
        migrations.AddField(
            model_name='user',
            name='period',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
