# Generated by Django 5.0.3 on 2024-10-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_user_year_community_enrolled_user_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year_community_enrolled',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
