# Generated by Django 5.0.3 on 2024-04-25 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_remove_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('media_uri', models.ImageField(upload_to='uploads/events/thumbnails/')),
                ('held_on', models.DateField()),
                ('budget', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.division')),
            ],
        ),
    ]
