# Generated by Django 5.0.3 on 2024-05-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
