# Generated by Django 5.0.3 on 2024-05-08 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_description_alter_event_name'),
        ('users', '0016_alter_user_division_id_alter_user_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='division_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.division'),
        ),
    ]
