# Generated by Django 5.0.3 on 2024-05-08 21:47

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_division_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='media_uri',
            field=models.ImageField(upload_to='uploads/events/thumbnails/', validators=[common.validators.validate_image_size]),
        ),
    ]
