# Generated by Django 5.0.3 on 2024-08-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_media_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
