# Generated by Django 5.0.3 on 2024-05-01 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_icon_uri_project_image_uri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailcontributorproject',
            name='member_nim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detailcontributorproject',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributors', to='projects.project'),
        ),
    ]
