# Generated by Django 5.0.3 on 2024-05-08 21:47

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_detailcontributorproject_member_nim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon_uri',
            field=models.ImageField(upload_to='uploads/projects/icons/', validators=[common.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_uri',
            field=models.ImageField(upload_to='uploads/projects/thumbnails/', validators=[common.validators.validate_image_size]),
        ),
    ]
