# Generated by Django 5.0.3 on 2024-05-09 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_division_id'),
        ('users', '0019_alter_division_logo_uri_alter_user_profile_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='division_id',
        ),
        migrations.CreateModel(
            name='DetailDivisionProject',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(default='system', max_length=255, null=True)),
                ('updated_by', models.CharField(default='system', max_length=255, null=True)),
                ('division_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='users.division')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='projects.project')),
            ],
        ),
    ]
