version: '3'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/app/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pastibukanjokowi
      - POSTGRES_USER=cci_postgres
      - POSTGRES_DB=cci_be

  web:
    build: .
    links:
        - postgres
    command: python manage.py runserver 0.0.0.0:8181
    volumes:
      - .:/app
    ports:
      - "8181:8181"
    depends_on:
        - postgres
    environment:
      env_file: .env

volumes:
    postgres_data: