version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: cci_web
      MYSQL_USER: remote
      MYSQL_PASSWORD: cciVpsYa?990
      MYSQL_ROOT_PASSWORD: cciVpsYa?990
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    links:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=cci_web
      - DATABASE_USER=remote
      - DATABASE_PASSWORD=cciVpsYa?990
      - DATABASE_HOST=103.187.147.80
      - DATABASE_PORT=3306
      - DATABASE_ENGINE=django.db.backends.mysql
      - JWT_SECRET_KEY=secret
      - SECRET_KEY=secret

volumes:
  db_data: