services:
  web:
    build: .
    links:
      - postgres
    command: "gunicorn cci_rebuild_be.wsgi:application --bind 0.0.0.0:8181"
    volumes:
      - .:/app
    ports:
      - "8181:8181"
    expose:
      - "8181"
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}

volumes:
  postgres_data:
