# Generated by Django 5.0.3 on 2024-05-08 21:47

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailnewsmedia',
            name='media_uri',
            field=models.ImageField(upload_to='uploads/news/media/', validators=[common.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='news',
            name='media_uri',
            field=models.ImageField(upload_to='uploads/news/thumbnails/', validators=[common.validators.validate_image_size]),
        ),
    ]
