# Generated by Django 5.0.3 on 2024-08-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_detailnewsmedia_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
