# Generated by Django 5.0.3 on 2024-03-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('telp', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('logo_uri', models.CharField(max_length=255, null=True)),
                ('title_website', models.CharField(max_length=255, null=True)),
                ('keyword', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
