# Generated by Django 5.0.3 on 2024-03-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_setting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='logo_uri',
            field=models.ImageField(upload_to='uploads/setting/'),
        ),
    ]
