# Generated by Django 5.0.3 on 2024-04-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_contact_is_active_alter_contact_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
