# Generated by Django 5.0.3 on 2024-04-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_contact_created_by_contact_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='logo_uri',
            field=models.ImageField(blank=True, upload_to='uploads/setting/'),
        ),
    ]
