# Generated by Django 5.0.3 on 2024-04-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_setting_logo_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='logo_uri',
            field=models.ImageField(upload_to='uploads/setting/'),
        ),
    ]
