# Generated by Django 5.0.3 on 2024-04-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_alter_setting_logo_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
