# Generated by Django 5.0.3 on 2024-04-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_alter_contact_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_by',
            field=models.CharField(default='system', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_by',
            field=models.CharField(default='system', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='created_by',
            field=models.CharField(default='system', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='setting',
            name='telp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title_website',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='setting',
            name='updated_by',
            field=models.CharField(default='system', max_length=255, null=True),
        ),
    ]
