# Generated by Django 5.0.3 on 2024-04-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_alter_setting_address_alter_setting_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
