# Generated by Django 5.0.3 on 2024-05-05 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_alter_contact_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='telp',
        ),
    ]
