# Generated by Django 5.0.3 on 2024-05-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_remove_setting_telp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='account_uri',
            field=models.CharField(default=42, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
