# Generated by Django 5.0.3 on 2024-05-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_contact_account_uri_alter_contact_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='visited_count',
        ),
    ]
