# Generated by Django 5.0.3 on 2024-05-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_remove_contact_visited_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='visited_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
