# Generated by Django 5.0.3 on 2024-05-08 21:47

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0022_setting_visited_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='icon_uri',
            field=models.ImageField(upload_to='uploads/contact/', validators=[common.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo_uri',
            field=models.ImageField(upload_to='uploads/setting/', validators=[common.validators.validate_image_size]),
        ),
    ]
