# Generated by Django 5.0.3 on 2024-05-03 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('issuer', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(default='system', max_length=255, null=True)),
                ('updated_by', models.CharField(default='system', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailContributorAward',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(default='system', max_length=255, null=True)),
                ('updated_by', models.CharField(default='system', max_length=255, null=True)),
                ('award_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributors', to='awards.award')),
                ('member_nim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
