name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 103.187.147.80
          username: cci-vps
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/Web-Profile-API/
            # Pull latest changes
            git pull origin main
            # Build and run containers using Docker Compose
            docker-compose down
            docker-compose up -d --build