name: Deploy to VPS

on:
  push:
    branches:
      - main
  PREPARE stmt FROM 'INSERT INTO `cci_web`.`users_user` (`nim`,`phone_number`,`nim`,`year_university_enrolled`,`name`,`phone_number`,`updated_at`,`updated_by`,`year_university_enrolled`,`active`,`role_id_id`,`division_id_id`) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 103.187.147.80
          username: cci-vps
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd ~/Web-Profile-API/
            # Pull latest changes
            git pull origin main
            # Build and run containers using Docker Compose
            docker-compose down
            docker-compose up -d --build